package(default_visibility = ["//visibility:public"])
licenses(["notice"]) # MIT license

cc_library(
  name = "libev-423a",
  includes= [
    ".",
  ],
  hdrs = [
    "ev.h",
    "ev++.h",
  ],
  srcs = [
    "libev.a",
  ],
  deps = [
  ],
)
